apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tire: application
data:
  REDIS_HOST: redis 
  CATALOGUE_HOST: catalogue 
  CATALOGUE_PORT: 8080
---
apiVersion: apps/v1
kind: deployment
metadata:
  name: cart
  namespace: roboshop
  # deployment labels
  labels:
    component: cart
    project: roboshop
    tire: application
spec:
  replicas: 1   # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: cart
      project: roboshop
      tire: application
    # This is pod definition
    template:
      metadata:
        labels:
          component: cart
          project: roboshop
          tire: application
  spec:
    containers:
      - name: cart
        image: sangala2025/cart:v1
    envFrom:
      - configMapRef:
          name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop

  labels: 
    component: cart
    project: roboshop 
    tire: application
spec:
  selectors:
    component: cart
    project: roboshop 
    tire: application
  ports:
    - protocol: TCP
      port: 8080 #service port
      targetPort: 8080 #container port
