apiVersion: apps/v1
kind: deployment
metadata:
  name: redis
  namespace: roboshop
  # deployment labels
  labels:
    component: redis
    project: roboshop 
    tire: Database
spec:
 # These are the labels replica set use to create pod replicas, this should match pod labels
  replicas: 1
  selectors:
    matchLabels:  
      component: redis
      project: roboshop 
      tire: Database
  # This is pod definition
  template:
    metadata:
      component: redis
      project: roboshop 
      tire: Database
spec:
  containers:
    - name: redis
      image: sangala2025/redis:v1 

#service
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop

  labels: 
    component: redis
    project: roboshop 
    tire: Database
spec:
  selectors:
    component: redis
    project: roboshop 
    tire: Database
  ports:
    - protocol: TCP
      port: 6379 #service port
      targetPort: 6379 #container port
